/**
 * Complete WebLLM model catalog with 100+ models.
 *
 * Each entry includes metadata for UI display, hardware compatibility
 * checks, and filtering: name, family, provider, parameter count,
 * estimated VRAM, context window, quantization, categories, and
 * hardware tier classification.
 *
 * Add new models by appending to MODEL_CATALOG and following the
 * existing pattern. The tier() helper auto-classifies by VRAM.
 */

export type ModelFamily =
  | "llama"
  | "qwen"
  | "phi"
  | "gemma"
  | "mistral"
  | "deepseek"
  | "smollm"
  | "olmo"
  | "stablelm"
  | "redpajama"
  | "tinyllama"
  | "ministral"
  | "hermes"
  | "other";

export type ModelCategory =
  | "general"
  | "coding"
  | "math"
  | "reasoning"
  | "vision"
  | "uncensored"
  | "embedding";

export type HardwareTier = "low" | "medium" | "high" | "ultra";

export interface CatalogModel {
  id: string;
  name: string;
  family: ModelFamily;
  provider: string;
  description: string;
  parameterCount: string;
  parameterCountNum: number; // in billions, for sorting
  vramRequired: number; // MB
  contextWindow: number;
  quantization: string;
  requiresF16: boolean;
  lowResource: boolean;
  categories: ModelCategory[];
  hardwareTier: HardwareTier;
  isRecommended?: boolean;
}

function tier(vram: number): HardwareTier {
  if (vram < 1500) return "low";
  if (vram < 4000) return "medium";
  if (vram < 8000) return "high";
  return "ultra";
}

export const MODEL_CATALOG: CatalogModel[] = [
  // ─── Qwen 3.5 ───
  {
    id: "Qwen3.5-0.8B-q4f16_1-MLC",
    name: "Qwen 3.5 0.8B",
    family: "qwen",
    provider: "Alibaba",
    description: "Latest Qwen 3.5 series, ultra-compact 0.8B model, great for quick responses on low-end devices",
    parameterCount: "0.8B",
    parameterCountNum: 0.8,
    vramRequired: 1629,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1629),
  },
  {
    id: "Qwen3.5-0.8B-q4f32_1-MLC",
    name: "Qwen 3.5 0.8B",
    family: "qwen",
    provider: "Alibaba",
    description: "Latest Qwen 3.5 series, ultra-compact 0.8B, f32 quantization for broader GPU support",
    parameterCount: "0.8B",
    parameterCountNum: 0.8,
    vramRequired: 1894,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1894),
  },
  {
    id: "Qwen3.5-0.8B-q0f16-MLC",
    name: "Qwen 3.5 0.8B (Full)",
    family: "qwen",
    provider: "Alibaba",
    description: "Full precision Qwen 3.5 0.8B, highest quality at small size",
    parameterCount: "0.8B",
    parameterCountNum: 0.8,
    vramRequired: 2660,
    contextWindow: 32768,
    quantization: "q0f16",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2660),
  },
  {
    id: "Qwen3.5-2B-q4f16_1-MLC",
    name: "Qwen 3.5 2B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 3.5 2B, excellent balance of speed and capability for everyday tasks",
    parameterCount: "2B",
    parameterCountNum: 2,
    vramRequired: 2245,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2245),
    isRecommended: true,
  },
  {
    id: "Qwen3.5-2B-q4f32_1-MLC",
    name: "Qwen 3.5 2B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 3.5 2B, f32 quantization, wider GPU compatibility",
    parameterCount: "2B",
    parameterCountNum: 2,
    vramRequired: 2592,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2592),
  },
  {
    id: "Qwen3.5-4B-q4f16_1-MLC",
    name: "Qwen 3.5 4B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 3.5 4B, strong mid-range model with excellent instruction following",
    parameterCount: "4B",
    parameterCountNum: 4,
    vramRequired: 3868,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(3868),
  },
  {
    id: "Qwen3.5-4B-q4f32_1-MLC",
    name: "Qwen 3.5 4B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 3.5 4B, f32 quantization for broader GPU support",
    parameterCount: "4B",
    parameterCountNum: 4,
    vramRequired: 4680,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(4680),
  },
  {
    id: "Qwen3.5-9B-q4f16_1-MLC",
    name: "Qwen 3.5 9B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 3.5 9B, top-tier model with near-GPT-4 quality, requires decent GPU",
    parameterCount: "9B",
    parameterCountNum: 9,
    vramRequired: 6433,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(6433),
  },
  {
    id: "Qwen3.5-9B-q4f32_1-MLC",
    name: "Qwen 3.5 9B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 3.5 9B, f32, wider GPU compatibility",
    parameterCount: "9B",
    parameterCountNum: 9,
    vramRequired: 7545,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(7545),
  },

  // ─── Qwen 3 ───
  {
    id: "Qwen3-0.6B-q4f16_1-MLC",
    name: "Qwen 3 0.6B",
    family: "qwen",
    provider: "Alibaba",
    description: "Tiny Qwen 3 model, fastest option, ideal for testing and ultra-low resource devices",
    parameterCount: "0.6B",
    parameterCountNum: 0.6,
    vramRequired: 1403,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1403),
  },
  {
    id: "Qwen3-0.6B-q4f32_1-MLC",
    name: "Qwen 3 0.6B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 3 0.6B with f32 quantization",
    parameterCount: "0.6B",
    parameterCountNum: 0.6,
    vramRequired: 1925,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1925),
  },
  {
    id: "Qwen3-0.6B-q0f16-MLC",
    name: "Qwen 3 0.6B (Full)",
    family: "qwen",
    provider: "Alibaba",
    description: "Full precision Qwen 3 0.6B",
    parameterCount: "0.6B",
    parameterCountNum: 0.6,
    vramRequired: 2220,
    contextWindow: 32768,
    quantization: "q0f16",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2220),
  },
  {
    id: "Qwen3-0.6B-q0f32-MLC",
    name: "Qwen 3 0.6B (Full f32)",
    family: "qwen",
    provider: "Alibaba",
    description: "Full precision Qwen 3 0.6B with f32",
    parameterCount: "0.6B",
    parameterCountNum: 0.6,
    vramRequired: 3843,
    contextWindow: 32768,
    quantization: "q0f32",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(3843),
  },
  {
    id: "Qwen3-1.7B-q4f16_1-MLC",
    name: "Qwen 3 1.7B",
    family: "qwen",
    provider: "Alibaba",
    description: "Compact Qwen 3 with strong reasoning for its size",
    parameterCount: "1.7B",
    parameterCountNum: 1.7,
    vramRequired: 2037,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2037),
  },
  {
    id: "Qwen3-1.7B-q4f32_1-MLC",
    name: "Qwen 3 1.7B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 3 1.7B with f32 quantization",
    parameterCount: "1.7B",
    parameterCountNum: 1.7,
    vramRequired: 2635,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2635),
  },
  {
    id: "Qwen3-4B-q4f16_1-MLC",
    name: "Qwen 3 4B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 3 4B, solid mid-range model with strong multilingual support",
    parameterCount: "4B",
    parameterCountNum: 4,
    vramRequired: 3432,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(3432),
  },
  {
    id: "Qwen3-4B-q4f32_1-MLC",
    name: "Qwen 3 4B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 3 4B with f32 quantization",
    parameterCount: "4B",
    parameterCountNum: 4,
    vramRequired: 4328,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(4328),
  },
  {
    id: "Qwen3-8B-q4f16_1-MLC",
    name: "Qwen 3 8B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 3 8B, powerful model rivaling much larger competitors",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 5696,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(5696),
  },
  {
    id: "Qwen3-8B-q4f32_1-MLC",
    name: "Qwen 3 8B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 3 8B with f32 quantization",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 6853,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(6853),
  },

  // ─── Qwen 2.5 ───
  {
    id: "Qwen2.5-0.5B-Instruct-q4f16_1-MLC",
    name: "Qwen 2.5 0.5B",
    family: "qwen",
    provider: "Alibaba",
    description: "Ultra-small instruction-tuned model, runs on virtually any device",
    parameterCount: "0.5B",
    parameterCountNum: 0.5,
    vramRequired: 945,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(945),
  },
  {
    id: "Qwen2.5-0.5B-Instruct-q4f32_1-MLC",
    name: "Qwen 2.5 0.5B",
    family: "qwen",
    provider: "Alibaba",
    description: "Ultra-small Qwen 2.5 with f32 quantization",
    parameterCount: "0.5B",
    parameterCountNum: 0.5,
    vramRequired: 1060,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1060),
  },
  {
    id: "Qwen2.5-1.5B-Instruct-q4f16_1-MLC",
    name: "Qwen 2.5 1.5B",
    family: "qwen",
    provider: "Alibaba",
    description: "Compact Qwen 2.5 with solid instruction following",
    parameterCount: "1.5B",
    parameterCountNum: 1.5,
    vramRequired: 1630,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1630),
  },
  {
    id: "Qwen2.5-1.5B-Instruct-q4f32_1-MLC",
    name: "Qwen 2.5 1.5B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 2.5 1.5B with f32 quantization",
    parameterCount: "1.5B",
    parameterCountNum: 1.5,
    vramRequired: 1889,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(1889),
  },
  {
    id: "Qwen2.5-3B-Instruct-q4f16_1-MLC",
    name: "Qwen 2.5 3B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 2.5 3B, great balance of quality and speed",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 2505,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(2505),
  },
  {
    id: "Qwen2.5-3B-Instruct-q4f32_1-MLC",
    name: "Qwen 2.5 3B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 2.5 3B with f32 quantization",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 2894,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(2894),
  },
  {
    id: "Qwen2.5-7B-Instruct-q4f16_1-MLC",
    name: "Qwen 2.5 7B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 2.5 7B, high-quality model for complex tasks",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 5107,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(5107),
  },
  {
    id: "Qwen2.5-7B-Instruct-q4f32_1-MLC",
    name: "Qwen 2.5 7B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 2.5 7B with f32 quantization",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 5900,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(5900),
  },

  // ─── Qwen 2.5 Coder ───
  {
    id: "Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC",
    name: "Qwen 2.5 Coder 0.5B",
    family: "qwen",
    provider: "Alibaba",
    description: "Tiny code-specialized model for basic code completion",
    parameterCount: "0.5B",
    parameterCountNum: 0.5,
    vramRequired: 945,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["coding"],
    hardwareTier: tier(945),
  },
  {
    id: "Qwen2.5-Coder-0.5B-Instruct-q4f32_1-MLC",
    name: "Qwen 2.5 Coder 0.5B",
    family: "qwen",
    provider: "Alibaba",
    description: "Tiny code model with f32 quantization",
    parameterCount: "0.5B",
    parameterCountNum: 0.5,
    vramRequired: 1060,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["coding"],
    hardwareTier: tier(1060),
  },
  {
    id: "Qwen2.5-Coder-1.5B-Instruct-q4f16_1-MLC",
    name: "Qwen 2.5 Coder 1.5B",
    family: "qwen",
    provider: "Alibaba",
    description: "Compact code model with strong generation capabilities",
    parameterCount: "1.5B",
    parameterCountNum: 1.5,
    vramRequired: 1630,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["coding"],
    hardwareTier: tier(1630),
  },
  {
    id: "Qwen2.5-Coder-1.5B-Instruct-q4f32_1-MLC",
    name: "Qwen 2.5 Coder 1.5B",
    family: "qwen",
    provider: "Alibaba",
    description: "Compact code model with f32 quantization",
    parameterCount: "1.5B",
    parameterCountNum: 1.5,
    vramRequired: 1889,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["coding"],
    hardwareTier: tier(1889),
  },
  {
    id: "Qwen2.5-Coder-3B-Instruct-q4f16_1-MLC",
    name: "Qwen 2.5 Coder 3B",
    family: "qwen",
    provider: "Alibaba",
    description: "Mid-range code model with excellent code understanding",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 2505,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["coding"],
    hardwareTier: tier(2505),
  },
  {
    id: "Qwen2.5-Coder-3B-Instruct-q4f32_1-MLC",
    name: "Qwen 2.5 Coder 3B",
    family: "qwen",
    provider: "Alibaba",
    description: "Mid-range code model with f32 quantization",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 2894,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["coding"],
    hardwareTier: tier(2894),
  },
  {
    id: "Qwen2.5-Coder-7B-Instruct-q4f16_1-MLC",
    name: "Qwen 2.5 Coder 7B",
    family: "qwen",
    provider: "Alibaba",
    description: "Top-tier code model, excellent for programming assistance",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 5107,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["coding"],
    hardwareTier: tier(5107),
    isRecommended: true,
  },
  {
    id: "Qwen2.5-Coder-7B-Instruct-q4f32_1-MLC",
    name: "Qwen 2.5 Coder 7B",
    family: "qwen",
    provider: "Alibaba",
    description: "Top-tier code model with f32 quantization",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 5900,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["coding"],
    hardwareTier: tier(5900),
  },

  // ─── Qwen 2.5 Math ───
  {
    id: "Qwen2.5-Math-1.5B-Instruct-q4f16_1-MLC",
    name: "Qwen 2.5 Math 1.5B",
    family: "qwen",
    provider: "Alibaba",
    description: "Specialized math model for problem-solving and calculations",
    parameterCount: "1.5B",
    parameterCountNum: 1.5,
    vramRequired: 1630,
    contextWindow: 4096,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["math"],
    hardwareTier: tier(1630),
  },
  {
    id: "Qwen2.5-Math-1.5B-Instruct-q4f32_1-MLC",
    name: "Qwen 2.5 Math 1.5B",
    family: "qwen",
    provider: "Alibaba",
    description: "Math model with f32 quantization",
    parameterCount: "1.5B",
    parameterCountNum: 1.5,
    vramRequired: 1889,
    contextWindow: 4096,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["math"],
    hardwareTier: tier(1889),
  },

  // ─── Qwen 2 ───
  {
    id: "Qwen2-0.5B-Instruct-q4f16_1-MLC",
    name: "Qwen 2 0.5B",
    family: "qwen",
    provider: "Alibaba",
    description: "Previous gen ultra-small Qwen model",
    parameterCount: "0.5B",
    parameterCountNum: 0.5,
    vramRequired: 945,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(945),
  },
  {
    id: "Qwen2-1.5B-Instruct-q4f16_1-MLC",
    name: "Qwen 2 1.5B",
    family: "qwen",
    provider: "Alibaba",
    description: "Previous gen compact Qwen model",
    parameterCount: "1.5B",
    parameterCountNum: 1.5,
    vramRequired: 1630,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1630),
  },
  {
    id: "Qwen2-1.5B-Instruct-q4f32_1-MLC",
    name: "Qwen 2 1.5B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 2 1.5B with f32 quantization",
    parameterCount: "1.5B",
    parameterCountNum: 1.5,
    vramRequired: 1889,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(1889),
  },
  {
    id: "Qwen2-7B-Instruct-q4f16_1-MLC",
    name: "Qwen 2 7B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 2 7B, previous gen but still capable",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 5107,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(5107),
  },
  {
    id: "Qwen2-7B-Instruct-q4f32_1-MLC",
    name: "Qwen 2 7B",
    family: "qwen",
    provider: "Alibaba",
    description: "Qwen 2 7B with f32 quantization",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 5900,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(5900),
  },

  // ─── Qwen 2 Math ───
  {
    id: "Qwen2-Math-1.5B-Instruct-q4f16_1-MLC",
    name: "Qwen 2 Math 1.5B",
    family: "qwen",
    provider: "Alibaba",
    description: "Math-specialized Qwen 2 model",
    parameterCount: "1.5B",
    parameterCountNum: 1.5,
    vramRequired: 1630,
    contextWindow: 4096,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["math"],
    hardwareTier: tier(1630),
  },
  {
    id: "Qwen2-Math-1.5B-Instruct-q4f32_1-MLC",
    name: "Qwen 2 Math 1.5B",
    family: "qwen",
    provider: "Alibaba",
    description: "Math Qwen 2 1.5B with f32",
    parameterCount: "1.5B",
    parameterCountNum: 1.5,
    vramRequired: 1889,
    contextWindow: 4096,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["math"],
    hardwareTier: tier(1889),
  },
  {
    id: "Qwen2-Math-7B-Instruct-q4f16_1-MLC",
    name: "Qwen 2 Math 7B",
    family: "qwen",
    provider: "Alibaba",
    description: "Large math-specialized Qwen 2 model",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 5107,
    contextWindow: 4096,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["math"],
    hardwareTier: tier(5107),
  },
  {
    id: "Qwen2-Math-7B-Instruct-q4f32_1-MLC",
    name: "Qwen 2 Math 7B",
    family: "qwen",
    provider: "Alibaba",
    description: "Large math Qwen 2 with f32",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 5900,
    contextWindow: 4096,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["math"],
    hardwareTier: tier(5900),
  },

  // ─── Llama 3.2 ───
  {
    id: "Llama-3.2-1B-Instruct-q4f32_1-MLC",
    name: "Llama 3.2 1B",
    family: "llama",
    provider: "Meta",
    description: "Meta's compact 1B model, fast and efficient for simple tasks",
    parameterCount: "1B",
    parameterCountNum: 1,
    vramRequired: 1129,
    contextWindow: 131072,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1129),
  },
  {
    id: "Llama-3.2-1B-Instruct-q4f16_1-MLC",
    name: "Llama 3.2 1B",
    family: "llama",
    provider: "Meta",
    description: "Meta's 1B model with f16 quantization",
    parameterCount: "1B",
    parameterCountNum: 1,
    vramRequired: 879,
    contextWindow: 131072,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(879),
  },
  {
    id: "Llama-3.2-1B-Instruct-q0f32-MLC",
    name: "Llama 3.2 1B (Full)",
    family: "llama",
    provider: "Meta",
    description: "Full precision Llama 3.2 1B",
    parameterCount: "1B",
    parameterCountNum: 1,
    vramRequired: 5106,
    contextWindow: 131072,
    quantization: "q0f32",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(5106),
  },
  {
    id: "Llama-3.2-1B-Instruct-q0f16-MLC",
    name: "Llama 3.2 1B (Full f16)",
    family: "llama",
    provider: "Meta",
    description: "Full precision f16 Llama 3.2 1B",
    parameterCount: "1B",
    parameterCountNum: 1,
    vramRequired: 2573,
    contextWindow: 131072,
    quantization: "q0f16",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2573),
  },
  {
    id: "Llama-3.2-3B-Instruct-q4f32_1-MLC",
    name: "Llama 3.2 3B",
    family: "llama",
    provider: "Meta",
    description: "Meta's 3B model, great quality-to-size ratio",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 2952,
    contextWindow: 131072,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2952),
    isRecommended: true,
  },
  {
    id: "Llama-3.2-3B-Instruct-q4f16_1-MLC",
    name: "Llama 3.2 3B",
    family: "llama",
    provider: "Meta",
    description: "Meta's 3B model with f16 quantization, smaller download",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 2264,
    contextWindow: 131072,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2264),
  },

  // ─── Llama 3.1 ───
  {
    id: "Llama-3.1-8B-Instruct-q4f32_1-MLC-1k",
    name: "Llama 3.1 8B (1K ctx)",
    family: "llama",
    provider: "Meta",
    description: "Llama 3.1 8B with reduced 1K context for lower VRAM usage",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 5296,
    contextWindow: 1024,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(5296),
  },
  {
    id: "Llama-3.1-8B-Instruct-q4f16_1-MLC-1k",
    name: "Llama 3.1 8B (1K ctx)",
    family: "llama",
    provider: "Meta",
    description: "Llama 3.1 8B f16 with 1K context",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 4598,
    contextWindow: 1024,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(4598),
  },
  {
    id: "Llama-3.1-8B-Instruct-q4f32_1-MLC",
    name: "Llama 3.1 8B",
    family: "llama",
    provider: "Meta",
    description: "Meta's flagship 8B model with 128K context, powerful and versatile",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 6101,
    contextWindow: 131072,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(6101),
  },
  {
    id: "Llama-3.1-8B-Instruct-q4f16_1-MLC",
    name: "Llama 3.1 8B",
    family: "llama",
    provider: "Meta",
    description: "Meta's 8B with f16, smaller download, same quality",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 5001,
    contextWindow: 131072,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(5001),
  },
  {
    id: "Llama-3.1-70B-Instruct-q3f16_1-MLC",
    name: "Llama 3.1 70B",
    family: "llama",
    provider: "Meta",
    description: "Massive 70B model, requires 32GB+ VRAM, GPT-4 class quality",
    parameterCount: "70B",
    parameterCountNum: 70,
    vramRequired: 31153,
    contextWindow: 131072,
    quantization: "q3f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(31153),
  },

  // ─── Llama 3 ───
  {
    id: "Llama-3-8B-Instruct-q4f32_1-MLC-1k",
    name: "Llama 3 8B (1K ctx)",
    family: "llama",
    provider: "Meta",
    description: "Llama 3 8B with 1K context for lower VRAM",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 5296,
    contextWindow: 1024,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(5296),
  },
  {
    id: "Llama-3-8B-Instruct-q4f16_1-MLC-1k",
    name: "Llama 3 8B (1K ctx)",
    family: "llama",
    provider: "Meta",
    description: "Llama 3 8B f16 with 1K context",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 4598,
    contextWindow: 1024,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(4598),
  },
  {
    id: "Llama-3-8B-Instruct-q4f32_1-MLC",
    name: "Llama 3 8B",
    family: "llama",
    provider: "Meta",
    description: "Meta's Llama 3 8B, solid general-purpose model",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 6101,
    contextWindow: 8192,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(6101),
  },
  {
    id: "Llama-3-8B-Instruct-q4f16_1-MLC",
    name: "Llama 3 8B",
    family: "llama",
    provider: "Meta",
    description: "Llama 3 8B with f16 quantization",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 5001,
    contextWindow: 8192,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(5001),
  },
  {
    id: "Llama-3-70B-Instruct-q3f16_1-MLC",
    name: "Llama 3 70B",
    family: "llama",
    provider: "Meta",
    description: "Massive Llama 3 70B, requires 32GB+ VRAM",
    parameterCount: "70B",
    parameterCountNum: 70,
    vramRequired: 31153,
    contextWindow: 8192,
    quantization: "q3f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(31153),
  },

  // ─── Llama 2 ───
  {
    id: "Llama-2-7b-chat-hf-q4f32_1-MLC-1k",
    name: "Llama 2 7B (1K ctx)",
    family: "llama",
    provider: "Meta",
    description: "Legacy Llama 2 with 1K context",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 5284,
    contextWindow: 1024,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(5284),
  },
  {
    id: "Llama-2-7b-chat-hf-q4f16_1-MLC-1k",
    name: "Llama 2 7B (1K ctx)",
    family: "llama",
    provider: "Meta",
    description: "Legacy Llama 2 f16 with 1K context",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 4619,
    contextWindow: 1024,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(4619),
  },
  {
    id: "Llama-2-7b-chat-hf-q4f32_1-MLC",
    name: "Llama 2 7B",
    family: "llama",
    provider: "Meta",
    description: "Legacy Llama 2 7B chat model",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 9109,
    contextWindow: 4096,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(9109),
  },
  {
    id: "Llama-2-7b-chat-hf-q4f16_1-MLC",
    name: "Llama 2 7B",
    family: "llama",
    provider: "Meta",
    description: "Legacy Llama 2 7B f16",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 6749,
    contextWindow: 4096,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(6749),
  },
  {
    id: "Llama-2-13b-chat-hf-q4f16_1-MLC",
    name: "Llama 2 13B",
    family: "llama",
    provider: "Meta",
    description: "Legacy Llama 2 13B, requires 12GB+ VRAM",
    parameterCount: "13B",
    parameterCountNum: 13,
    vramRequired: 11814,
    contextWindow: 4096,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(11814),
  },

  // ─── DeepSeek R1 ───
  {
    id: "DeepSeek-R1-Distill-Qwen-7B-q4f16_1-MLC",
    name: "DeepSeek R1 Qwen 7B",
    family: "deepseek",
    provider: "DeepSeek",
    description: "DeepSeek R1 distilled into Qwen 7B, excellent reasoning with chain-of-thought",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 5107,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["reasoning"],
    hardwareTier: tier(5107),
    isRecommended: true,
  },
  {
    id: "DeepSeek-R1-Distill-Qwen-7B-q4f32_1-MLC",
    name: "DeepSeek R1 Qwen 7B",
    family: "deepseek",
    provider: "DeepSeek",
    description: "DeepSeek R1 Qwen 7B with f32 quantization",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 5900,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["reasoning"],
    hardwareTier: tier(5900),
  },
  {
    id: "DeepSeek-R1-Distill-Llama-8B-q4f32_1-MLC",
    name: "DeepSeek R1 Llama 8B",
    family: "deepseek",
    provider: "DeepSeek",
    description: "DeepSeek R1 distilled into Llama 8B, strong reasoning capabilities",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 6101,
    contextWindow: 131072,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["reasoning"],
    hardwareTier: tier(6101),
  },
  {
    id: "DeepSeek-R1-Distill-Llama-8B-q4f16_1-MLC",
    name: "DeepSeek R1 Llama 8B",
    family: "deepseek",
    provider: "DeepSeek",
    description: "DeepSeek R1 Llama 8B with f16",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 5001,
    contextWindow: 131072,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["reasoning"],
    hardwareTier: tier(5001),
  },

  // ─── Hermes (Uncensored) ───
  {
    id: "Hermes-3-Llama-3.2-3B-q4f32_1-MLC",
    name: "Hermes 3 Llama 3B",
    family: "hermes",
    provider: "NousResearch",
    description: "Hermes 3, uncensored, instruction-tuned Llama 3.2 3B with minimal refusals",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 2952,
    contextWindow: 131072,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general", "uncensored"],
    hardwareTier: tier(2952),
  },
  {
    id: "Hermes-3-Llama-3.2-3B-q4f16_1-MLC",
    name: "Hermes 3 Llama 3B",
    family: "hermes",
    provider: "NousResearch",
    description: "Hermes 3 Llama 3B f16, uncensored model with minimal refusals",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 2264,
    contextWindow: 131072,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general", "uncensored"],
    hardwareTier: tier(2264),
  },
  {
    id: "Hermes-3-Llama-3.1-8B-q4f32_1-MLC",
    name: "Hermes 3 Llama 8B",
    family: "hermes",
    provider: "NousResearch",
    description: "Hermes 3 8B, uncensored, powerful model with function calling support",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 5779,
    contextWindow: 131072,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general", "uncensored"],
    hardwareTier: tier(5779),
  },
  {
    id: "Hermes-3-Llama-3.1-8B-q4f16_1-MLC",
    name: "Hermes 3 Llama 8B",
    family: "hermes",
    provider: "NousResearch",
    description: "Hermes 3 8B f16, uncensored with function calling",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 4876,
    contextWindow: 131072,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general", "uncensored"],
    hardwareTier: tier(4876),
  },
  {
    id: "Hermes-2-Theta-Llama-3-8B-q4f16_1-MLC",
    name: "Hermes 2 Theta 8B",
    family: "hermes",
    provider: "NousResearch",
    description: "Hermes 2 Theta, uncensored Llama 3 merge with enhanced capabilities",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 4976,
    contextWindow: 8192,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general", "uncensored"],
    hardwareTier: tier(4976),
  },
  {
    id: "Hermes-2-Theta-Llama-3-8B-q4f32_1-MLC",
    name: "Hermes 2 Theta 8B",
    family: "hermes",
    provider: "NousResearch",
    description: "Hermes 2 Theta f32, uncensored Llama 3 merge",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 6051,
    contextWindow: 8192,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general", "uncensored"],
    hardwareTier: tier(6051),
  },
  {
    id: "Hermes-2-Pro-Llama-3-8B-q4f16_1-MLC",
    name: "Hermes 2 Pro 8B",
    family: "hermes",
    provider: "NousResearch",
    description: "Hermes 2 Pro, uncensored with structured output and function calling",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 4976,
    contextWindow: 8192,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general", "uncensored"],
    hardwareTier: tier(4976),
  },
  {
    id: "Hermes-2-Pro-Llama-3-8B-q4f32_1-MLC",
    name: "Hermes 2 Pro 8B",
    family: "hermes",
    provider: "NousResearch",
    description: "Hermes 2 Pro f32, uncensored model",
    parameterCount: "8B",
    parameterCountNum: 8,
    vramRequired: 6051,
    contextWindow: 8192,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general", "uncensored"],
    hardwareTier: tier(6051),
  },
  {
    id: "Hermes-2-Pro-Mistral-7B-q4f16_1-MLC",
    name: "Hermes 2 Pro Mistral 7B",
    family: "hermes",
    provider: "NousResearch",
    description: "Hermes 2 Pro on Mistral, uncensored with strong instruction following",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 4033,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: false,
    categories: ["general", "uncensored"],
    hardwareTier: tier(4033),
  },
  {
    id: "OpenHermes-2.5-Mistral-7B-q4f16_1-MLC",
    name: "OpenHermes 2.5 Mistral 7B",
    family: "hermes",
    provider: "Teknium",
    description: "OpenHermes 2.5, uncensored Mistral fine-tune with broad knowledge",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 4573,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: false,
    categories: ["general", "uncensored"],
    hardwareTier: tier(4573),
  },
  {
    id: "NeuralHermes-2.5-Mistral-7B-q4f16_1-MLC",
    name: "NeuralHermes 2.5 Mistral 7B",
    family: "hermes",
    provider: "Teknium",
    description: "NeuralHermes, uncensored Mistral variant with DPO training",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 4573,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: false,
    categories: ["general", "uncensored"],
    hardwareTier: tier(4573),
  },

  // ─── Phi (Microsoft) ───
  {
    id: "Phi-4-mini-instruct-q4f16_1-MLC",
    name: "Phi-4 Mini",
    family: "phi",
    provider: "Microsoft",
    description: "Latest Phi-4 Mini, Microsoft's most capable small model with strong reasoning",
    parameterCount: "3.8B",
    parameterCountNum: 3.8,
    vramRequired: 3438,
    contextWindow: 16384,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general", "reasoning"],
    hardwareTier: tier(3438),
    isRecommended: true,
  },
  {
    id: "Phi-4-mini-instruct-q4f32_1-MLC",
    name: "Phi-4 Mini",
    family: "phi",
    provider: "Microsoft",
    description: "Phi-4 Mini with f32 quantization",
    parameterCount: "3.8B",
    parameterCountNum: 3.8,
    vramRequired: 4221,
    contextWindow: 16384,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general", "reasoning"],
    hardwareTier: tier(4221),
  },
  {
    id: "Phi-3.5-mini-instruct-q4f16_1-MLC",
    name: "Phi-3.5 Mini",
    family: "phi",
    provider: "Microsoft",
    description: "Phi-3.5 Mini, solid reasoning and instruction following",
    parameterCount: "3.8B",
    parameterCountNum: 3.8,
    vramRequired: 3672,
    contextWindow: 131072,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(3672),
  },
  {
    id: "Phi-3.5-mini-instruct-q4f32_1-MLC",
    name: "Phi-3.5 Mini",
    family: "phi",
    provider: "Microsoft",
    description: "Phi-3.5 Mini with f32 quantization",
    parameterCount: "3.8B",
    parameterCountNum: 3.8,
    vramRequired: 5483,
    contextWindow: 131072,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(5483),
  },
  {
    id: "Phi-3.5-mini-instruct-q4f16_1-MLC-1k",
    name: "Phi-3.5 Mini (1K ctx)",
    family: "phi",
    provider: "Microsoft",
    description: "Phi-3.5 Mini with 1K context for lower VRAM",
    parameterCount: "3.8B",
    parameterCountNum: 3.8,
    vramRequired: 2520,
    contextWindow: 1024,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2520),
  },
  {
    id: "Phi-3.5-mini-instruct-q4f32_1-MLC-1k",
    name: "Phi-3.5 Mini (1K ctx)",
    family: "phi",
    provider: "Microsoft",
    description: "Phi-3.5 Mini f32 with 1K context",
    parameterCount: "3.8B",
    parameterCountNum: 3.8,
    vramRequired: 3179,
    contextWindow: 1024,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(3179),
  },
  {
    id: "Phi-3.5-vision-instruct-q4f16_1-MLC",
    name: "Phi-3.5 Vision",
    family: "phi",
    provider: "Microsoft",
    description: "Phi-3.5 with vision capabilities, can understand images",
    parameterCount: "4.2B",
    parameterCountNum: 4.2,
    vramRequired: 3952,
    contextWindow: 4096,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["vision"],
    hardwareTier: tier(3952),
  },
  {
    id: "Phi-3.5-vision-instruct-q4f32_1-MLC",
    name: "Phi-3.5 Vision",
    family: "phi",
    provider: "Microsoft",
    description: "Phi-3.5 Vision with f32 quantization",
    parameterCount: "4.2B",
    parameterCountNum: 4.2,
    vramRequired: 5880,
    contextWindow: 4096,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["vision"],
    hardwareTier: tier(5880),
  },
  {
    id: "Phi-3-mini-4k-instruct-q4f16_1-MLC",
    name: "Phi-3 Mini",
    family: "phi",
    provider: "Microsoft",
    description: "Phi-3 Mini, solid general model with 4K context",
    parameterCount: "3.8B",
    parameterCountNum: 3.8,
    vramRequired: 3672,
    contextWindow: 4096,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(3672),
  },
  {
    id: "Phi-3-mini-4k-instruct-q4f32_1-MLC",
    name: "Phi-3 Mini",
    family: "phi",
    provider: "Microsoft",
    description: "Phi-3 Mini with f32 quantization",
    parameterCount: "3.8B",
    parameterCountNum: 3.8,
    vramRequired: 5483,
    contextWindow: 4096,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(5483),
  },
  {
    id: "Phi-3-mini-4k-instruct-q4f16_1-MLC-1k",
    name: "Phi-3 Mini (1K ctx)",
    family: "phi",
    provider: "Microsoft",
    description: "Phi-3 Mini with 1K context",
    parameterCount: "3.8B",
    parameterCountNum: 3.8,
    vramRequired: 2520,
    contextWindow: 1024,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2520),
  },
  {
    id: "Phi-3-mini-4k-instruct-q4f32_1-MLC-1k",
    name: "Phi-3 Mini (1K ctx)",
    family: "phi",
    provider: "Microsoft",
    description: "Phi-3 Mini f32 with 1K context",
    parameterCount: "3.8B",
    parameterCountNum: 3.8,
    vramRequired: 3179,
    contextWindow: 1024,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(3179),
  },
  {
    id: "phi-2-q4f16_1-MLC",
    name: "Phi-2",
    family: "phi",
    provider: "Microsoft",
    description: "Legacy Phi-2, older but still decent for basic tasks",
    parameterCount: "2.7B",
    parameterCountNum: 2.7,
    vramRequired: 3054,
    contextWindow: 2048,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(3054),
  },
  {
    id: "phi-2-q4f32_1-MLC",
    name: "Phi-2",
    family: "phi",
    provider: "Microsoft",
    description: "Phi-2 with f32 quantization",
    parameterCount: "2.7B",
    parameterCountNum: 2.7,
    vramRequired: 4032,
    contextWindow: 2048,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(4032),
  },
  {
    id: "phi-2-q4f16_1-MLC-1k",
    name: "Phi-2 (1K ctx)",
    family: "phi",
    provider: "Microsoft",
    description: "Phi-2 with 1K context",
    parameterCount: "2.7B",
    parameterCountNum: 2.7,
    vramRequired: 2132,
    contextWindow: 1024,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2132),
  },
  {
    id: "phi-2-q4f32_1-MLC-1k",
    name: "Phi-2 (1K ctx)",
    family: "phi",
    provider: "Microsoft",
    description: "Phi-2 f32 with 1K context",
    parameterCount: "2.7B",
    parameterCountNum: 2.7,
    vramRequired: 2740,
    contextWindow: 1024,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2740),
  },
  {
    id: "phi-1_5-q4f16_1-MLC",
    name: "Phi-1.5",
    family: "phi",
    provider: "Microsoft",
    description: "Very small legacy Phi model, code-focused",
    parameterCount: "1.3B",
    parameterCountNum: 1.3,
    vramRequired: 1210,
    contextWindow: 2048,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: true,
    categories: ["coding"],
    hardwareTier: tier(1210),
  },
  {
    id: "phi-1_5-q4f32_1-MLC",
    name: "Phi-1.5",
    family: "phi",
    provider: "Microsoft",
    description: "Phi-1.5 with f32 quantization",
    parameterCount: "1.3B",
    parameterCountNum: 1.3,
    vramRequired: 1682,
    contextWindow: 2048,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["coding"],
    hardwareTier: tier(1682),
  },
  {
    id: "phi-1_5-q4f16_1-MLC-1k",
    name: "Phi-1.5 (1K ctx)",
    family: "phi",
    provider: "Microsoft",
    description: "Phi-1.5 with 1K context",
    parameterCount: "1.3B",
    parameterCountNum: 1.3,
    vramRequired: 1210,
    contextWindow: 1024,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: true,
    categories: ["coding"],
    hardwareTier: tier(1210),
  },
  {
    id: "phi-1_5-q4f32_1-MLC-1k",
    name: "Phi-1.5 (1K ctx)",
    family: "phi",
    provider: "Microsoft",
    description: "Phi-1.5 f32 with 1K context",
    parameterCount: "1.3B",
    parameterCountNum: 1.3,
    vramRequired: 1682,
    contextWindow: 1024,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["coding"],
    hardwareTier: tier(1682),
  },

  // ─── Gemma (Google) ───
  {
    id: "gemma3-1b-it-q4f16_1-MLC",
    name: "Gemma 3 1B",
    family: "gemma",
    provider: "Google",
    description: "Google's latest Gemma 3 1B, tiny but surprisingly capable",
    parameterCount: "1B",
    parameterCountNum: 1,
    vramRequired: 711,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(711),
    isRecommended: true,
  },
  {
    id: "gemma-2-2b-it-q4f16_1-MLC",
    name: "Gemma 2 2B",
    family: "gemma",
    provider: "Google",
    description: "Google's efficient 2B model, great balance of quality and speed",
    parameterCount: "2B",
    parameterCountNum: 2,
    vramRequired: 1895,
    contextWindow: 4096,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(1895),
  },
  {
    id: "gemma-2-2b-it-q4f32_1-MLC",
    name: "Gemma 2 2B",
    family: "gemma",
    provider: "Google",
    description: "Gemma 2 2B with f32, no shader-f16 required",
    parameterCount: "2B",
    parameterCountNum: 2,
    vramRequired: 2509,
    contextWindow: 4096,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(2509),
  },
  {
    id: "gemma-2-2b-it-q4f16_1-MLC-1k",
    name: "Gemma 2 2B (1K ctx)",
    family: "gemma",
    provider: "Google",
    description: "Gemma 2 2B with 1K context for lower VRAM",
    parameterCount: "2B",
    parameterCountNum: 2,
    vramRequired: 1583,
    contextWindow: 1024,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1583),
  },
  {
    id: "gemma-2-2b-it-q4f32_1-MLC-1k",
    name: "Gemma 2 2B (1K ctx)",
    family: "gemma",
    provider: "Google",
    description: "Gemma 2 2B f32 with 1K context",
    parameterCount: "2B",
    parameterCountNum: 2,
    vramRequired: 1885,
    contextWindow: 1024,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1885),
  },
  {
    id: "gemma-2-9b-it-q4f16_1-MLC",
    name: "Gemma 2 9B",
    family: "gemma",
    provider: "Google",
    description: "Gemma 2 9B, Google's powerful model, requires 6GB+ VRAM",
    parameterCount: "9B",
    parameterCountNum: 9,
    vramRequired: 6422,
    contextWindow: 4096,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(6422),
  },
  {
    id: "gemma-2-9b-it-q4f32_1-MLC",
    name: "Gemma 2 9B",
    family: "gemma",
    provider: "Google",
    description: "Gemma 2 9B with f32 quantization",
    parameterCount: "9B",
    parameterCountNum: 9,
    vramRequired: 8383,
    contextWindow: 4096,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(8383),
  },
  {
    id: "gemma-2-2b-jpn-it-q4f16_1-MLC",
    name: "Gemma 2 2B Japanese",
    family: "gemma",
    provider: "Google",
    description: "Gemma 2 2B optimized for Japanese language",
    parameterCount: "2B",
    parameterCountNum: 2,
    vramRequired: 1895,
    contextWindow: 4096,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1895),
  },
  {
    id: "gemma-2-2b-jpn-it-q4f32_1-MLC",
    name: "Gemma 2 2B Japanese",
    family: "gemma",
    provider: "Google",
    description: "Gemma 2 2B Japanese with f32",
    parameterCount: "2B",
    parameterCountNum: 2,
    vramRequired: 2509,
    contextWindow: 4096,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2509),
  },
  {
    id: "gemma-2b-it-q4f16_1-MLC",
    name: "Gemma 1 2B",
    family: "gemma",
    provider: "Google",
    description: "Original Gemma 2B, legacy model",
    parameterCount: "2B",
    parameterCountNum: 2,
    vramRequired: 1477,
    contextWindow: 8192,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(1477),
  },
  {
    id: "gemma-2b-it-q4f32_1-MLC",
    name: "Gemma 1 2B",
    family: "gemma",
    provider: "Google",
    description: "Gemma 1 2B with f32",
    parameterCount: "2B",
    parameterCountNum: 2,
    vramRequired: 1751,
    contextWindow: 8192,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(1751),
  },
  {
    id: "gemma-2b-it-q4f16_1-MLC-1k",
    name: "Gemma 1 2B (1K ctx)",
    family: "gemma",
    provider: "Google",
    description: "Gemma 1 2B with 1K context",
    parameterCount: "2B",
    parameterCountNum: 2,
    vramRequired: 1477,
    contextWindow: 1024,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1477),
  },
  {
    id: "gemma-2b-it-q4f32_1-MLC-1k",
    name: "Gemma 1 2B (1K ctx)",
    family: "gemma",
    provider: "Google",
    description: "Gemma 1 2B f32 with 1K context",
    parameterCount: "2B",
    parameterCountNum: 2,
    vramRequired: 1751,
    contextWindow: 1024,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1751),
  },

  // ─── Mistral ───
  {
    id: "Mistral-7B-Instruct-v0.3-q4f16_1-MLC",
    name: "Mistral 7B v0.3",
    family: "mistral",
    provider: "Mistral AI",
    description: "Mistral 7B v0.3, strong open model with extended vocabulary",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 4573,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(4573),
  },
  {
    id: "Mistral-7B-Instruct-v0.3-q4f32_1-MLC",
    name: "Mistral 7B v0.3",
    family: "mistral",
    provider: "Mistral AI",
    description: "Mistral 7B v0.3 with f32, no shader-f16 needed",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 5619,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(5619),
  },
  {
    id: "Mistral-7B-Instruct-v0.2-q4f16_1-MLC",
    name: "Mistral 7B v0.2",
    family: "mistral",
    provider: "Mistral AI",
    description: "Mistral 7B v0.2, older but proven and reliable",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 4573,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(4573),
  },

  // ─── WizardMath ───
  {
    id: "WizardMath-7B-V1.1-q4f16_1-MLC",
    name: "WizardMath 7B",
    family: "mistral",
    provider: "WizardLM",
    description: "Specialized math model with strong problem-solving capabilities",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 4573,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: false,
    categories: ["math"],
    hardwareTier: tier(4573),
  },

  // ─── SmolLM2 ───
  {
    id: "SmolLM2-1.7B-Instruct-q4f16_1-MLC",
    name: "SmolLM2 1.7B",
    family: "smollm",
    provider: "HuggingFace",
    description: "HuggingFace's compact model, designed for on-device inference",
    parameterCount: "1.7B",
    parameterCountNum: 1.7,
    vramRequired: 1774,
    contextWindow: 8192,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1774),
  },
  {
    id: "SmolLM2-1.7B-Instruct-q4f32_1-MLC",
    name: "SmolLM2 1.7B",
    family: "smollm",
    provider: "HuggingFace",
    description: "SmolLM2 1.7B with f32 quantization",
    parameterCount: "1.7B",
    parameterCountNum: 1.7,
    vramRequired: 2692,
    contextWindow: 8192,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2692),
  },
  {
    id: "SmolLM2-360M-Instruct-q0f16-MLC",
    name: "SmolLM2 360M (Full)",
    family: "smollm",
    provider: "HuggingFace",
    description: "Ultra-tiny 360M model at full precision",
    parameterCount: "360M",
    parameterCountNum: 0.36,
    vramRequired: 872,
    contextWindow: 8192,
    quantization: "q0f16",
    requiresF16: true,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(872),
  },
  {
    id: "SmolLM2-360M-Instruct-q0f32-MLC",
    name: "SmolLM2 360M (Full f32)",
    family: "smollm",
    provider: "HuggingFace",
    description: "Ultra-tiny 360M model at full f32 precision",
    parameterCount: "360M",
    parameterCountNum: 0.36,
    vramRequired: 1744,
    contextWindow: 8192,
    quantization: "q0f32",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1744),
  },
  {
    id: "SmolLM2-360M-Instruct-q4f16_1-MLC",
    name: "SmolLM2 360M",
    family: "smollm",
    provider: "HuggingFace",
    description: "Tiny 360M model, the smallest usable chat model",
    parameterCount: "360M",
    parameterCountNum: 0.36,
    vramRequired: 376,
    contextWindow: 8192,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(376),
  },
  {
    id: "SmolLM2-360M-Instruct-q4f32_1-MLC",
    name: "SmolLM2 360M",
    family: "smollm",
    provider: "HuggingFace",
    description: "Tiny 360M model with f32, runs on anything",
    parameterCount: "360M",
    parameterCountNum: 0.36,
    vramRequired: 580,
    contextWindow: 8192,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(580),
  },
  {
    id: "SmolLM2-135M-Instruct-q0f16-MLC",
    name: "SmolLM2 135M",
    family: "smollm",
    provider: "HuggingFace",
    description: "Smallest model available, 135M params, mainly for testing",
    parameterCount: "135M",
    parameterCountNum: 0.135,
    vramRequired: 360,
    contextWindow: 8192,
    quantization: "q0f16",
    requiresF16: true,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(360),
  },
  {
    id: "SmolLM2-135M-Instruct-q0f32-MLC",
    name: "SmolLM2 135M",
    family: "smollm",
    provider: "HuggingFace",
    description: "Smallest model with f32, for testing purposes",
    parameterCount: "135M",
    parameterCountNum: 0.135,
    vramRequired: 719,
    contextWindow: 8192,
    quantization: "q0f32",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(719),
  },

  // ─── OLMo ───
  {
    id: "OLMo-2-0425-1B-Instruct-q4f16_1-MLC",
    name: "OLMo 2 1B",
    family: "olmo",
    provider: "AI2",
    description: "AI2's fully open-source OLMo 2 1B, transparent training data",
    parameterCount: "1B",
    parameterCountNum: 1,
    vramRequired: 1777,
    contextWindow: 4096,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1777),
  },
  {
    id: "OLMo-2-0425-1B-Instruct-q4f32_1-MLC",
    name: "OLMo 2 1B",
    family: "olmo",
    provider: "AI2",
    description: "OLMo 2 1B with f32 quantization",
    parameterCount: "1B",
    parameterCountNum: 1,
    vramRequired: 2412,
    contextWindow: 4096,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2412),
  },
  {
    id: "OLMo-2-1124-7B-Instruct-q4f16_1-MLC",
    name: "OLMo 2 7B",
    family: "olmo",
    provider: "AI2",
    description: "OLMo 2 7B, fully open source, competitive with closed models",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 6479,
    contextWindow: 4096,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(6479),
  },
  {
    id: "OLMo-2-1124-7B-Instruct-q4f32_1-MLC",
    name: "OLMo 2 7B",
    family: "olmo",
    provider: "AI2",
    description: "OLMo 2 7B with f32",
    parameterCount: "7B",
    parameterCountNum: 7,
    vramRequired: 9086,
    contextWindow: 4096,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(9086),
  },

  // ─── StableLM ───
  {
    id: "stablelm-2-zephyr-1_6b-q4f16_1-MLC",
    name: "StableLM Zephyr 1.6B",
    family: "stablelm",
    provider: "Stability AI",
    description: "Compact chat model from Stability AI",
    parameterCount: "1.6B",
    parameterCountNum: 1.6,
    vramRequired: 2045,
    contextWindow: 4096,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(2045),
  },
  {
    id: "stablelm-2-zephyr-1_6b-q4f32_1-MLC",
    name: "StableLM Zephyr 1.6B",
    family: "stablelm",
    provider: "Stability AI",
    description: "StableLM Zephyr with f32",
    parameterCount: "1.6B",
    parameterCountNum: 1.6,
    vramRequired: 2461,
    contextWindow: 4096,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(2461),
  },
  {
    id: "stablelm-2-zephyr-1_6b-q4f16_1-MLC-1k",
    name: "StableLM Zephyr 1.6B (1K)",
    family: "stablelm",
    provider: "Stability AI",
    description: "StableLM Zephyr with 1K context",
    parameterCount: "1.6B",
    parameterCountNum: 1.6,
    vramRequired: 1512,
    contextWindow: 1024,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1512),
  },
  {
    id: "stablelm-2-zephyr-1_6b-q4f32_1-MLC-1k",
    name: "StableLM Zephyr 1.6B (1K)",
    family: "stablelm",
    provider: "Stability AI",
    description: "StableLM Zephyr f32 with 1K context",
    parameterCount: "1.6B",
    parameterCountNum: 1.6,
    vramRequired: 1847,
    contextWindow: 1024,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(1847),
  },

  // ─── RedPajama ───
  {
    id: "RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC",
    name: "RedPajama 3B",
    family: "redpajama",
    provider: "Together AI",
    description: "Open-source 3B chat model",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 2972,
    contextWindow: 2048,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(2972),
  },
  {
    id: "RedPajama-INCITE-Chat-3B-v1-q4f32_1-MLC",
    name: "RedPajama 3B",
    family: "redpajama",
    provider: "Together AI",
    description: "RedPajama 3B with f32",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 3928,
    contextWindow: 2048,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: false,
    categories: ["general"],
    hardwareTier: tier(3928),
  },
  {
    id: "RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC-1k",
    name: "RedPajama 3B (1K)",
    family: "redpajama",
    provider: "Together AI",
    description: "RedPajama 3B with 1K context",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 2041,
    contextWindow: 1024,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2041),
  },
  {
    id: "RedPajama-INCITE-Chat-3B-v1-q4f32_1-MLC-1k",
    name: "RedPajama 3B (1K)",
    family: "redpajama",
    provider: "Together AI",
    description: "RedPajama 3B f32 with 1K context",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 2558,
    contextWindow: 1024,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2558),
  },

  // ─── TinyLlama ───
  {
    id: "TinyLlama-1.1B-Chat-v1.0-q4f16_1-MLC",
    name: "TinyLlama 1.1B v1.0",
    family: "tinyllama",
    provider: "TinyLlama",
    description: "Tiny 1.1B model, fast for basic tasks",
    parameterCount: "1.1B",
    parameterCountNum: 1.1,
    vramRequired: 697,
    contextWindow: 2048,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(697),
  },
  {
    id: "TinyLlama-1.1B-Chat-v1.0-q4f32_1-MLC",
    name: "TinyLlama 1.1B v1.0",
    family: "tinyllama",
    provider: "TinyLlama",
    description: "TinyLlama v1.0 with f32",
    parameterCount: "1.1B",
    parameterCountNum: 1.1,
    vramRequired: 840,
    contextWindow: 2048,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(840),
  },
  {
    id: "TinyLlama-1.1B-Chat-v1.0-q4f16_1-MLC-1k",
    name: "TinyLlama 1.1B v1.0 (1K)",
    family: "tinyllama",
    provider: "TinyLlama",
    description: "TinyLlama v1.0 with 1K context",
    parameterCount: "1.1B",
    parameterCountNum: 1.1,
    vramRequired: 675,
    contextWindow: 1024,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(675),
  },
  {
    id: "TinyLlama-1.1B-Chat-v1.0-q4f32_1-MLC-1k",
    name: "TinyLlama 1.1B v1.0 (1K)",
    family: "tinyllama",
    provider: "TinyLlama",
    description: "TinyLlama v1.0 f32 with 1K context",
    parameterCount: "1.1B",
    parameterCountNum: 1.1,
    vramRequired: 796,
    contextWindow: 1024,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(796),
  },
  {
    id: "TinyLlama-1.1B-Chat-v0.4-q4f16_1-MLC",
    name: "TinyLlama 1.1B v0.4",
    family: "tinyllama",
    provider: "TinyLlama",
    description: "Older TinyLlama version",
    parameterCount: "1.1B",
    parameterCountNum: 1.1,
    vramRequired: 697,
    contextWindow: 2048,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(697),
  },
  {
    id: "TinyLlama-1.1B-Chat-v0.4-q4f32_1-MLC",
    name: "TinyLlama 1.1B v0.4",
    family: "tinyllama",
    provider: "TinyLlama",
    description: "TinyLlama v0.4 with f32",
    parameterCount: "1.1B",
    parameterCountNum: 1.1,
    vramRequired: 840,
    contextWindow: 2048,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(840),
  },
  {
    id: "TinyLlama-1.1B-Chat-v0.4-q4f16_1-MLC-1k",
    name: "TinyLlama 1.1B v0.4 (1K)",
    family: "tinyllama",
    provider: "TinyLlama",
    description: "TinyLlama v0.4 with 1K context",
    parameterCount: "1.1B",
    parameterCountNum: 1.1,
    vramRequired: 675,
    contextWindow: 1024,
    quantization: "q4f16_1",
    requiresF16: true,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(675),
  },
  {
    id: "TinyLlama-1.1B-Chat-v0.4-q4f32_1-MLC-1k",
    name: "TinyLlama 1.1B v0.4 (1K)",
    family: "tinyllama",
    provider: "TinyLlama",
    description: "TinyLlama v0.4 f32 with 1K context",
    parameterCount: "1.1B",
    parameterCountNum: 1.1,
    vramRequired: 796,
    contextWindow: 1024,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(796),
  },

  // ─── Ministral ───
  {
    id: "Ministral-3-3B-Instruct-2512-BF16-q4f16_1-MLC",
    name: "Ministral 3B Instruct",
    family: "ministral",
    provider: "Mistral AI",
    description: "Mistral's compact 3B instruction model",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 2864,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2864),
  },
  {
    id: "Ministral-3-3B-Instruct-2512-BF16-q4f32_1-MLC",
    name: "Ministral 3B Instruct",
    family: "ministral",
    provider: "Mistral AI",
    description: "Ministral 3B Instruct with f32",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 3532,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(3532),
  },
  {
    id: "Ministral-3-3B-Reasoning-2512-q4f16_1-MLC",
    name: "Ministral 3B Reasoning",
    family: "ministral",
    provider: "Mistral AI",
    description: "Ministral 3B tuned for reasoning tasks",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 2864,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["reasoning"],
    hardwareTier: tier(2864),
  },
  {
    id: "Ministral-3-3B-Reasoning-2512-q4f32_1-MLC",
    name: "Ministral 3B Reasoning",
    family: "ministral",
    provider: "Mistral AI",
    description: "Ministral 3B Reasoning with f32",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 3532,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["reasoning"],
    hardwareTier: tier(3532),
  },
  {
    id: "Ministral-3-3B-Base-2512-q4f16_1-MLC",
    name: "Ministral 3B Base",
    family: "ministral",
    provider: "Mistral AI",
    description: "Ministral 3B base model (not instruction-tuned)",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 2864,
    contextWindow: 32768,
    quantization: "q4f16_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(2864),
  },
  {
    id: "Ministral-3-3B-Base-2512-q4f32_1-MLC",
    name: "Ministral 3B Base",
    family: "ministral",
    provider: "Mistral AI",
    description: "Ministral 3B Base with f32",
    parameterCount: "3B",
    parameterCountNum: 3,
    vramRequired: 3532,
    contextWindow: 32768,
    quantization: "q4f32_1",
    requiresF16: false,
    lowResource: true,
    categories: ["general"],
    hardwareTier: tier(3532),
  },
];

// Exclude embedding models, they're not chat models

export const DEFAULT_MODEL_ID = "Qwen3.5-2B-q4f16_1-MLC";

export function getCatalogModel(id: string): CatalogModel | undefined {
  return MODEL_CATALOG.find((m) => m.id === id);
}

export function getModelsByFamily(family: ModelFamily): CatalogModel[] {
  return MODEL_CATALOG.filter((m) => m.family === family);
}

export function getModelsByCategory(category: ModelCategory): CatalogModel[] {
  return MODEL_CATALOG.filter((m) => m.categories.includes(category));
}

export function getRecommendedModels(): CatalogModel[] {
  return MODEL_CATALOG.filter((m) => m.isRecommended);
}

export function getModelsForVRAM(vramMB: number): CatalogModel[] {
  return MODEL_CATALOG.filter((m) => m.vramRequired <= vramMB);
}

export const FAMILY_LABELS: Record<ModelFamily, string> = {
  llama: "Llama (Meta)",
  qwen: "Qwen (Alibaba)",
  phi: "Phi (Microsoft)",
  gemma: "Gemma (Google)",
  mistral: "Mistral",
  deepseek: "DeepSeek",
  smollm: "SmolLM (HuggingFace)",
  olmo: "OLMo (AI2)",
  stablelm: "StableLM (Stability)",
  redpajama: "RedPajama",
  tinyllama: "TinyLlama",
  ministral: "Ministral (Mistral)",
  hermes: "Hermes (NousResearch)",
  other: "Other",
};

export const CATEGORY_LABELS: Record<ModelCategory, string> = {
  general: "General",
  coding: "Code",
  math: "Math",
  reasoning: "Reasoning",
  vision: "Vision",
  uncensored: "Uncensored",
  embedding: "Embedding",
};

export const TIER_LABELS: Record<HardwareTier, { label: string; color: string; description: string }> = {
  low: { label: "Low", color: "green", description: "< 1.5 GB VRAM, runs on most devices" },
  medium: { label: "Medium", color: "yellow", description: "1.5–4 GB VRAM, needs a decent GPU" },
  high: { label: "High", color: "orange", description: "4–8 GB VRAM, needs a good GPU" },
  ultra: { label: "Ultra", color: "red", description: "8+ GB VRAM, needs high-end GPU" },
};
